print("=== MENU DE INSCRIÇÃO DA MARATONA ===")
print("1 - Maratona Completa")
print("2 - Meia Maratona")
print("3 - Corrida de Estreia")
opcao = int(input("Escolha o número da suacategoria: "))
print("\n--- Resultado ---")